VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "FormatStruct"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public vDisplayName As String
Public vIsBold As Boolean
Public vIsItalic As Boolean
Public vFontName As String
Public vFontSize As Integer
Public vFontColor As Long
Public vCellColor As Long

